{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31m\u001b[0m\u001b[33mWarning\u001b[0m \"deno jupyter\" is unstable and might change in the future.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m============================================================\n",
      "\u001b[1;31mDeno has panicked. This is a bug in Deno. Please report this\n",
      "\u001b[1;31mat https://github.com/denoland/deno/issues/new.\n",
      "\u001b[1;31mIf you can reliably reproduce this panic, include the\n",
      "\u001b[1;31mreproduction steps and re-run with the RUST_BACKTRACE=1 env\n",
      "\u001b[1;31mvar set and include the backtrace in your report.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mPlatform: linux x86_64\n",
      "\u001b[1;31mVersion: 1.41.3\n",
      "\u001b[1;31mArgs: [\"/home/mrk/.deno/bin/deno\", \"jupyter\", \"--kernel\", \"--conn\", \"/home/mrk/.local/share/jupyter/runtime/kernel-v2-11411BApTZza8Bbe.json\"]\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mthread 'main' panicked at cli/util/logger.rs:79:5:\n",
      "\u001b[1;31mCould not install logger.: SetLoggerError(())\n",
      "\u001b[1;31mnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import $ from \"https://deno.land/x/dax@0.39.1/mod.ts\";\n",
    "\n",
    "const test = await $`deno lint --json`.stdout(\"piped\").stderr(\"piped\")\n",
    "  .captureCombined().noThrow();\n",
    "\n",
    "export interface Diagnostic {\n",
    "  range: {\n",
    "    start: { line: number; col: number; bytePos: number };\n",
    "    end: { line: number; col: number; bytePos: number };\n",
    "  };\n",
    "  filename: string;\n",
    "  message: string;\n",
    "  code: string;\n",
    "  hint: string;\n",
    "}\n",
    "\n",
    "export interface LintResults {\n",
    "  diagnostics: Diagnostic[];\n",
    "}\n",
    "\n",
    "const jsonOutput: LintResults = JSON.parse(test.combined);\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31m\u001b[0m\u001b[33mWarning\u001b[0m \"deno jupyter\" is unstable and might change in the future.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m============================================================\n",
      "\u001b[1;31mDeno has panicked. This is a bug in Deno. Please report this\n",
      "\u001b[1;31mat https://github.com/denoland/deno/issues/new.\n",
      "\u001b[1;31mIf you can reliably reproduce this panic, include the\n",
      "\u001b[1;31mreproduction steps and re-run with the RUST_BACKTRACE=1 env\n",
      "\u001b[1;31mvar set and include the backtrace in your report.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mPlatform: linux x86_64\n",
      "\u001b[1;31mVersion: 1.41.3\n",
      "\u001b[1;31mArgs: [\"/home/mrk/.deno/bin/deno\", \"jupyter\", \"--kernel\", \"--conn\", \"/home/mrk/.local/share/jupyter/runtime/kernel-v2-11411BApTZza8Bbe.json\"]\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mthread 'main' panicked at cli/util/logger.rs:79:5:\n",
      "\u001b[1;31mCould not install logger.: SetLoggerError(())\n",
      "\u001b[1;31mnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "interface Diagnostic {\n",
    "  range: {\n",
    "    start: { line: number; col: number; bytePos: number };\n",
    "    end: { line: number; col: number; bytePos: number };\n",
    "  };\n",
    "  filename: string;\n",
    "  message: string;\n",
    "  code: string;\n",
    "  hint: string;\n",
    "}\n",
    "\n",
    "interface LintResults {\n",
    "  diagnostics: Diagnostic[];\n",
    "}\n",
    "\n",
    "const groupedByCode = (jsonOutput as LintResults).diagnostics.reduce(\n",
    "  (acc, diagnostic) => {\n",
    "    const { code } = diagnostic;\n",
    "    if (!acc[code]) {\n",
    "      acc[code] = [];\n",
    "    }\n",
    "    acc[code].push(diagnostic);\n",
    "    return acc;\n",
    "  },\n",
    "  {} as Record<string, Diagnostic[]>,\n",
    ");\n",
    "\n",
    "for (const [code, errors] of Object.entries(groupedByCode)) {\n",
    "  console.log(`${code}: ${errors.length}`);\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31m\u001b[0m\u001b[33mWarning\u001b[0m \"deno jupyter\" is unstable and might change in the future.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m============================================================\n",
      "\u001b[1;31mDeno has panicked. This is a bug in Deno. Please report this\n",
      "\u001b[1;31mat https://github.com/denoland/deno/issues/new.\n",
      "\u001b[1;31mIf you can reliably reproduce this panic, include the\n",
      "\u001b[1;31mreproduction steps and re-run with the RUST_BACKTRACE=1 env\n",
      "\u001b[1;31mvar set and include the backtrace in your report.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mPlatform: linux x86_64\n",
      "\u001b[1;31mVersion: 1.41.3\n",
      "\u001b[1;31mArgs: [\"/home/mrk/.deno/bin/deno\", \"jupyter\", \"--kernel\", \"--conn\", \"/home/mrk/.local/share/jupyter/runtime/kernel-v2-11411BApTZza8Bbe.json\"]\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mthread 'main' panicked at cli/util/logger.rs:79:5:\n",
      "\u001b[1;31mCould not install logger.: SetLoggerError(())\n",
      "\u001b[1;31mnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import { toFileUrl } from \"std/path/mod.ts\";\n",
    "\n",
    "interface Diagnostic {\n",
    "  range: {\n",
    "    start: { line: number; col: number; bytePos: number };\n",
    "    end: { line: number; col: number; bytePos: number };\n",
    "  };\n",
    "  filename: string;\n",
    "  message: string;\n",
    "  code: string;\n",
    "  hint: string;\n",
    "}\n",
    "\n",
    "interface LintResults {\n",
    "  diagnostics: Diagnostic[];\n",
    "}\n",
    "\n",
    "const cwd = new URL(\"./\", toFileUrl(Deno.cwd())).pathname;\n",
    "\n",
    "const filenamesAndCountsByCode: Record<\n",
    "  string,\n",
    "  { files: string[]; count: number }\n",
    "> = Object.keys(groupedByCode).reduce((acc, code) => {\n",
    "  const diagnostics = groupedByCode[code];\n",
    "  const filenames = diagnostics.map((diagnostic) =>\n",
    "    diagnostic.filename.replace(cwd, \"\")\n",
    "  );\n",
    "\n",
    "  const count = diagnostics.length;\n",
    "\n",
    "  const uniqueFilenames = [...new Set(filenames)];\n",
    "\n",
    "  acc[code] = {\n",
    "    files: uniqueFilenames,\n",
    "    count: count,\n",
    "  };\n",
    "\n",
    "  return acc;\n",
    "}, {} as Record<string, { files: string[]; count: number }>);\n",
    "\n",
    "console.log(filenamesAndCountsByCode);\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Deno",
   "language": "typescript",
   "name": "deno"
  },
  "language_info": {
   "file_extension": ".ts",
   "mimetype": "text/x.typescript",
   "name": "typescript",
   "nb_converter": "script",
   "pygments_lexer": "typescript",
   "version": "5.3.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
